### PR TITLE
Add 4.X Patches

### PR DESCRIPTION
**Pull request by AcK77**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by substanc3-dev** [comment]
Are you sure those are correct? Those don't seem right to me.

**Comment by AcK77** [comment]
I don't own a 4.x switch to try... But there are 2 different peoples who tried and said me it works fine! So...

**Comment by Ced2911** [comment]
Working for me

**Comment by substanc3-dev** [comment]
No.

**Comment by AileenLumina** [comment]
It would be helpful if you could explain why you closed the PR and what needs fixing or improvement.

**Review by ghost — COMMENTED** [review]
can't make build

**Comment by AileenLumina** [comment]
https://github.com/nx-python/hekate-ipl-4x/releases/tag/v1.0.0 There you go.

**Comment by magicseb** [comment]
Working for me

https://github.com/magicseb/hekate-ipl-50x/releases/tag/v1.0.0

Binary available : ipl4x

**Comment by alwe2710** [comment]
Works for me as well on 4.1.0

**Comment by Noah670** [comment]
Nice works fine on 4.10.

**Pull request closed without merging**
